/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Clases.Bolsas;
import Clases.DaoBolsas;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;

/**
 *
 * @author Hackerman
 */
public class Actualizar extends javax.swing.JFrame {
     DefaultListModel modelo = new DefaultListModel();
    private void crearModelo() throws SQLException{
        modelo.clear();
        List<Bolsas> lista = new ArrayList<>();
        lista = DaoBolsas.listaBolsas();
        for(Bolsas bolsa:lista){
                modelo.addElement(bolsa);
            }
    }

    /**
     * Creates new form Actualizar
     */
    public Actualizar() {
        initComponents();
        try{
            this.crearModelo();
        } catch (SQLException ex){
            Logger.getLogger(Lista.class.getName()).log(Level.SEVERE, null, ex);
        }
        jListActualizarLista.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldActualizarNombre = new javax.swing.JTextField();
        jTextFieldActualizarModelo = new javax.swing.JTextField();
        jLabelActualizar = new javax.swing.JLabel();
        jLabelActualizarColor = new javax.swing.JLabel();
        jButtonActualizar = new javax.swing.JButton();
        jTextFieldActualizarColor = new javax.swing.JTextField();
        jLabelActualizarMaterial = new javax.swing.JLabel();
        jTextFieldActualizarMaterial = new javax.swing.JTextField();
        jLabelActualizarTamanio = new javax.swing.JLabel();
        jTextFieldActualizarTamanio = new javax.swing.JTextField();
        jLabelActualizarPrecio = new javax.swing.JLabel();
        jTextFieldActualizarPrecio = new javax.swing.JTextField();
        jLabelActualizarNombre = new javax.swing.JLabel();
        jLabelActualizarModelo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListActualizarLista = new javax.swing.JList<>();
        jLabelID = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextFieldActualizarNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldActualizarNombreActionPerformed(evt);
            }
        });

        jLabelActualizar.setText("Actualizar Bolsa");

        jLabelActualizarColor.setText("Color:");

        jButtonActualizar.setText("Actualizar");
        jButtonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActualizarActionPerformed(evt);
            }
        });

        jLabelActualizarMaterial.setText("Material:");

        jLabelActualizarTamanio.setText("Tamanio:");

        jLabelActualizarPrecio.setText("Precio:");

        jLabelActualizarNombre.setText("Nombre:");

        jLabelActualizarModelo.setText("Modelo");

        jListActualizarLista.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jListActualizarLista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListActualizarListaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jListActualizarLista);

        jLabelID.setText("ID:");

        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelActualizarMaterial)
                                    .addComponent(jLabelActualizarTamanio)
                                    .addComponent(jLabelActualizarPrecio)
                                    .addComponent(jLabelActualizarModelo)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabelActualizarNombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabelActualizarColor)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelID)
                                .addGap(88, 88, 88)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldActualizarNombre)
                            .addComponent(jTextFieldActualizarColor)
                            .addComponent(jTextFieldActualizarMaterial)
                            .addComponent(jTextFieldActualizarTamanio)
                            .addComponent(jTextFieldActualizarPrecio)
                            .addComponent(jTextFieldActualizarModelo, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButtonActualizar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonActualizar)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                                .addComponent(jLabelID))
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelActualizarNombre)
                            .addComponent(jTextFieldActualizarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldActualizarColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelActualizarColor))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelActualizarMaterial)
                            .addComponent(jTextFieldActualizarMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelActualizarTamanio)
                            .addComponent(jTextFieldActualizarTamanio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelActualizarPrecio)
                            .addComponent(jTextFieldActualizarPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelActualizarModelo)
                            .addComponent(jTextFieldActualizarModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldActualizarNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldActualizarNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldActualizarNombreActionPerformed

    private void jListActualizarListaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListActualizarListaMouseClicked
        if(evt.getClickCount() == 1){
            int index = jListActualizarLista.getSelectedIndex();
            Bolsas bolsa = (Bolsas)modelo.getElementAt(index);
            jLabel1.setText(""+bolsa.getId());
            jTextFieldActualizarNombre.setText(bolsa.getNombreBolsas());
            jTextFieldActualizarColor.setText(bolsa.getColor());
            jTextFieldActualizarMaterial.setText(bolsa.getMaterial());
            jTextFieldActualizarTamanio.setText(""+bolsa.getTamanio());
            jTextFieldActualizarPrecio.setText(Double.toString(bolsa.getPrecio()));
            jTextFieldActualizarModelo.setText(Integer.toString(bolsa.getModelo()));
            
            
        }
        
    }//GEN-LAST:event_jListActualizarListaMouseClicked

    private void jButtonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActualizarActionPerformed
        String nombreBolsa=jTextFieldActualizarNombre.getText();
        String colorBolsa=jTextFieldActualizarColor.getText();
        String materialBolsa=jTextFieldActualizarMaterial.getText();
        
        String x=jTextFieldActualizarTamanio.getText();
        double tamanio=Double.parseDouble(x);
        
        String y=jTextFieldActualizarPrecio.getText();
        double precio=Double.parseDouble(y);
        
        String z=jTextFieldActualizarModelo.getText();
        int modeloB=Integer.parseInt(z);
        String a=jLabel1.getText();
        int id=Integer.parseInt(a);
        Bolsas bolsa =new Bolsas(id, nombreBolsa, materialBolsa, colorBolsa, tamanio, precio, modeloB);
        
        try{
            DaoBolsas.update(bolsa);
        } catch (SQLException ex){
            Logger.getLogger(Actualizar.class.getName()).log(Level.SEVERE, null, ex);
        }
        finally{
            jTextFieldActualizarNombre.setText("");
            jTextFieldActualizarColor.setText("");
            jTextFieldActualizarMaterial.setText("");
            jTextFieldActualizarTamanio.setText("");
            jTextFieldActualizarPrecio.setText("");
            jTextFieldActualizarModelo.setText("");
            try{
                this.crearModelo();
            } catch (SQLException ex){
                Logger.getLogger(Actualizar.class.getName()).log(Level.SEVERE, null, ex);
            }
        jListActualizarLista.setModel(modelo);
        }
        
    }//GEN-LAST:event_jButtonActualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Actualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Actualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Actualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Actualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Actualizar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonActualizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelActualizar;
    private javax.swing.JLabel jLabelActualizarColor;
    private javax.swing.JLabel jLabelActualizarMaterial;
    private javax.swing.JLabel jLabelActualizarModelo;
    private javax.swing.JLabel jLabelActualizarNombre;
    private javax.swing.JLabel jLabelActualizarPrecio;
    private javax.swing.JLabel jLabelActualizarTamanio;
    private javax.swing.JLabel jLabelID;
    private javax.swing.JList<String> jListActualizarLista;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldActualizarColor;
    private javax.swing.JTextField jTextFieldActualizarMaterial;
    private javax.swing.JTextField jTextFieldActualizarModelo;
    private javax.swing.JTextField jTextFieldActualizarNombre;
    private javax.swing.JTextField jTextFieldActualizarPrecio;
    private javax.swing.JTextField jTextFieldActualizarTamanio;
    // End of variables declaration//GEN-END:variables
}
